const NAME = "BAR CRAFT倶楽部 KAMOGAWA｜Authentic Cocktail Bar";
const ADDRESS = "〒600-8012 京都府京都市下京区斎藤町123 RAKUAS木屋町 4F";
const PHONE = "075-365-8038";
const MAP = "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(NAME + " " + ADDRESS);
const INSTAGRAM = "https://www.instagram.com/craftclub.kamogawa/";

const faqs = [
  ["場所はどこですか？", `${ADDRESS}です。鴨川沿い、RAKUAS木屋町の4階にあります。`],
  ["最寄り駅から何分ですか？", "阪急 京都河原町駅から徒歩1分、京阪 祇園四条駅から徒歩3分です。"],
  ["営業時間と定休日は？", "火曜日から土曜日は19:00〜翌2:00です。日曜日・月曜日は定休日です。"],
  ["バーだけ利用できますか？", "はい。BAR CRAFT倶楽部 KAMOGAWAのみのご利用も歓迎しています。"],
  ["どのようなお酒を楽しめますか？", "バーテンダー監修のクラフトカクテルやウイスキーなど、多彩なドリンクを用意しています。"],
  ["ルーフトップはありますか？", "5階の屋上ルーフトップで、鴨川や京都の街並みを眺めながらバータイムを楽しめます。"],
  ["同じフロアに飲食店はありますか？", "同じ4階に姉妹店のWAGYU SUKIYAKI GIONがあります。すき焼きの後の一杯にも利用できます。"],
  ["Where is the bar located?", "It is on the 4th floor of RAKUAS Kiyamachi, a one-minute walk from Kyoto-kawaramachi Station and a three-minute walk from Gion-shijo Station."]
];
const jp = ["BAR CRAFT倶楽部 KAMOGAWA","BAR CRAFT倶楽部 鴨川","クラフト倶楽部 KAMOGAWA","クラフト倶楽部 鴨川","京都 バー","木屋町 バー","河原町 バー","祇園四条 バー","鴨川 バー","京都 カクテルバー","木屋町 カクテルバー","河原町 カクテルバー","祇園四条 カクテルバー","京都 オーセンティックバー","木屋町 オーセンティックバー","京都 クラフトカクテル","木屋町 クラフトカクテル","京都 ウイスキー バー","木屋町 ウイスキー","河原町 ウイスキー","京都 ルーフトップバー","鴨川 ルーフトップバー","木屋町 ルーフトップ","京都 夜景 バー","鴨川が見えるバー","京都河原町駅 バー","京都河原町駅 徒歩1分 バー","祇園四条駅 バー","祇園四条駅 徒歩3分 バー","斎藤町 バー","RAKUAS木屋町 バー","京都 深夜 バー","木屋町 深夜2時 バー","京都 二軒目 バー","河原町 二軒目","祇園四条 二軒目","京都 食後 バー","木屋町 食後の一杯","京都 一人飲み バー","木屋町 一人飲み","京都 観光 バー","京都 ナイトライフ","木屋町 ナイトライフ","鴨川沿い バー","京都屋上バー","京都 カクテル","木屋町 カクテル","河原町 カクテル","祇園四条 カクテル","京都 ウイスキー","バー予約 京都","木屋町 バー 営業時間","河原町 バー 営業時間","祇園四条 バー 営業時間","京都 火曜日 バー","京都 水曜日 バー","京都 木曜日 バー","京都 金曜日 バー","京都 土曜日 バー","京都 19時 バー","京都 翌2時まで バー","Authentic Cocktail Bar 京都","WAGYU SUKIYAKI GION 食後","すき焼き 食後 バー 京都","鴨川 夜景 カクテル","京都 街並み ルーフトップ","木屋町 屋上テラス","河原町 屋上テラス","京都 バーテンダー カクテル","京都 クラフトカクテルバー","下京区 バー","下京区 カクテルバー","四条河原町 バー","四条河原町 カクテル","京都駅周辺ではなく河原町 バー","木屋町通 バー","鴨川 バータイム","京都 大人 バー","京都 夜 カクテル","京都 バー Instagram","CRAFT CLUB KAMOGAWA","CRAFT CLUB 京都","KAMOGAWA cocktail bar","カモガワ カクテルバー","クラフトクラブ カモガワ","京都 新しいバー","木屋町 新しいバー","京都 2026 オープン バー","木屋町 2026 オープン","京都河原町 ナイトバー","祇園四条 ナイトバー","先斗町近く バー","四条大橋近く バー","鴨川 四条 バー","京都 ルーフトップ カクテル","木屋町 テラス バー","京都 夜景 カクテルバー","河原町 ウイスキーバー","祇園四条 ウイスキーバー","京都 カクテル 営業時間","BAR CRAFT倶楽部 電話","BAR CRAFT倶楽部 住所","BAR CRAFT倶楽部 営業時間","BAR CRAFT倶楽部 Instagram"];
const en = ["BAR CRAFT CLUB KAMOGAWA","CRAFT CLUB KAMOGAWA","authentic cocktail bar Kyoto","cocktail bar Kyoto","cocktail bar Kiyamachi","cocktail bar Kawaramachi","cocktail bar Gion Shijo","bar near Kyoto Kawaramachi Station","bar near Gion Shijo Station","Kyoto rooftop bar","Kamo River rooftop bar","bar overlooking Kamo River","craft cocktails Kyoto","whisky bar Kyoto","whisky bar Kiyamachi","Kyoto nightlife","Kiyamachi nightlife","late night bar Kyoto","bar open until 2am Kyoto","Kyoto bar opening hours","Kiyamachi bar opening hours","Kyoto local bar","Kyoto evening drinks","Kyoto after dinner bar","second stop bar Kyoto","solo drinking Kyoto","bar for travelers Kyoto","Kyoto city view bar","rooftop drinks Kyoto","Kamo River bar","bar by Kamo River","Shimogyo Ward bar","Saitocho bar","RAKUAS Kiyamachi bar","Kyoto cocktail experience","Japanese cocktail bar Kyoto","bartender crafted cocktails Kyoto","Kyoto whisky and cocktails","Kyoto rooftop terrace","Kiyamachi rooftop terrace","Kawaramachi rooftop bar","Gion Shijo rooftop bar","bar one minute from Kyoto Kawaramachi","bar three minutes from Gion Shijo","Kyoto Tuesday night bar","Kyoto Wednesday night bar","Kyoto Thursday night bar","Kyoto Friday night bar","Kyoto Saturday night bar","Kyoto bar 7pm","Kyoto bar 19:00","Kyoto bar 2am","cocktails near Shijo Bridge","bar near Shijo Bridge","bar near Pontocho","night drinks near Pontocho","cocktails near Kamo River","whisky near Kamo River","Kyoto skyline drinks","Kyoto cityscape rooftop","Kiyamachi authentic bar","Kawaramachi authentic bar","Gion authentic cocktail bar","Kyoto craft cocktail lounge","Kiyamachi craft cocktail lounge","Kyoto bar Instagram","craftclub kamogawa Instagram","BAR CRAFT CLUB address","BAR CRAFT CLUB phone","BAR CRAFT CLUB hours","BAR CRAFT CLUB directions","where to drink cocktails in Kyoto","where to drink whisky in Kyoto","Kyoto night out","Kiyamachi night out","Kawaramachi evening bar","Gion Shijo evening bar","rooftop bar Japan Kyoto","cocktail lounge Kyoto","Kyoto bar only visit welcome","bar after sukiyaki Kyoto","WAGYU SUKIYAKI GION bar","drinks after wagyu sukiyaki","Kyoto rooftop cocktail","Kamo River night view","Kyoto riverside nightlife","Kiyamachi riverside bar","Kyoto bar for one","Kyoto bar with terrace","Kyoto rooftop whisky","Kyoto rooftop cocktails","Kyoto cocktail bar directions","Kyoto cocktail bar phone number","Kyoto cocktail bar reservation info","Kyoto local cocktail experience","Kyoto evening rooftop","Kyoto travel nightlife","Kyoto visitor cocktail bar","Kyoto downtown cocktail bar","downtown Kyoto bar","Shijo Kawaramachi cocktail bar","Shijo Kawaramachi whisky bar","Kiyamachi drinks","Kawaramachi drinks","Gion Shijo drinks"];

const jsonLd = {
  "@context":"https://schema.org","@type":"BarOrPub",name:NAME,alternateName:["BAR CRAFT CLUB KAMOGAWA","BAR CRAFT倶楽部 鴨川"],url:"https://bar-craft-club-kamogawa.vercel.app/",telephone:PHONE,description:"京都・木屋町の鴨川沿いでクラフトカクテルとウイスキーを楽しめるオーセンティックカクテルバー。",address:{"@type":"PostalAddress",postalCode:"600-8012",addressRegion:"京都府",addressLocality:"京都市下京区",streetAddress:"斎藤町123 RAKUAS木屋町 4F",addressCountry:"JP"},servesCuisine:"Cocktail Bar",hasMap:MAP,sameAs:[INSTAGRAM],openingHoursSpecification:["Tuesday","Wednesday","Thursday","Friday","Saturday"].map(day=>({"@type":"OpeningHoursSpecification",dayOfWeek:`https://schema.org/${day}`,opens:"19:00",closes:"02:00"}))
};
const faqLd = {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};

export default function Home(){return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqLd)}}/>
  <header><a className="brand" href="#top">CRAFT <span>CLUB</span></a><nav><a href="#story">特徴</a><a href="#info">店舗情報</a><a href="#access">アクセス</a><a href="#faq">FAQ</a><a href="#english">English</a></nav></header>
  <main id="top"><section className="hero"><div className="eyebrow">KIYAMACHI · KYOTO</div><h1><span className="title-line">BAR CRAFT<span>倶楽部</span></span><br/>KAMOGAWA</h1><p className="lead">Authentic Cocktail Bar</p><p>鴨川の流れと京都の夜景を傍らに。<br/>クラフトカクテルとウイスキーを楽しむ、木屋町のバー。</p><div className="actions"><a className="primary" href={MAP}>Google Maps</a><a href={INSTAGRAM}>Instagram</a></div></section>
  <section id="story" className="split"><div><p className="kicker">BY THE KAMO RIVER</p><h2>京都の夜を、<br/>一杯の中に。</h2></div><div><p>京都河原町駅から徒歩1分、祇園四条駅から徒歩3分。BAR CRAFT倶楽部 KAMOGAWAは、木屋町の鴨川沿いにあるオーセンティックカクテルバーです。</p><p>バーテンダー・坪井吉文監修のクラフトカクテルやウイスキーなど、多彩なドリンクを用意しています。バーだけのご利用も歓迎しています。</p></div></section>
  <section className="feature"><p className="kicker">ROOFTOP</p><h2>川の音、街の灯り。</h2><p>5階の屋上ルーフトップでは、鴨川や京都の街並みを眺めながらバータイムをお楽しみいただけます。</p></section>
  <section id="info"><p className="kicker">INFORMATION</p><h2>店舗情報</h2><dl><div><dt>店名</dt><dd>{NAME}</dd></div><div><dt>業態</dt><dd>オーセンティックカクテルバー</dd></div><div><dt>住所</dt><dd>{ADDRESS}</dd></div><div><dt>電話</dt><dd><a href="tel:0753658038">{PHONE}</a></dd></div><div><dt>営業時間</dt><dd>火曜日〜土曜日 19:00〜翌2:00</dd></div><div><dt>定休日</dt><dd>日曜日・月曜日</dd></div><div><dt>Instagram</dt><dd><a href={INSTAGRAM}>@craftclub.kamogawa</a></dd></div></dl></section>
  <section id="access" className="access"><p className="kicker">ACCESS</p><h2>鴨川沿い、木屋町へ。</h2><p>{ADDRESS}</p><ul><li>阪急「京都河原町駅」から徒歩1分</li><li>京阪「祇園四条駅」から徒歩3分</li></ul><a className="primary" href={MAP}>Googleマップで開く</a></section>
  <section className="sister"><p className="kicker">SISTER RESTAURANT</p><h2>お食事から、食後の一杯まで。</h2><p>同じ4階には姉妹店「WAGYU SUKIYAKI GION」がございます。すき焼きを楽しんだ後の一杯はもちろん、BAR CRAFT倶楽部 KAMOGAWAのみのご利用も歓迎しております。</p></section>
  <section id="faq"><p className="kicker">FAQ</p><h2>よくあるご質問</h2><div className="faqs">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section id="english" className="english"><p className="kicker">ENGLISH GUIDE</p><h2>BAR CRAFT CLUB KAMOGAWA</h2><p>BAR CRAFT CLUB KAMOGAWA is an authentic cocktail bar by the Kamo River in Kiyamachi, Kyoto. Enjoy bartender-supervised craft cocktails, whisky and rooftop views of the river and Kyoto cityscape.</p><dl><div><dt>Address</dt><dd>RAKUAS Kiyamachi 4F, 123 Saitocho, Shimogyo Ward, Kyoto 600-8012, Japan</dd></div><div><dt>Access</dt><dd>1 minute on foot from Hankyu Kyoto-kawaramachi Station; 3 minutes from Keihan Gion-shijo Station</dd></div><div><dt>Hours</dt><dd>Tuesday–Saturday, 7:00 pm–2:00 am</dd></div><div><dt>Closed</dt><dd>Sunday and Monday</dd></div><div><dt>Contact</dt><dd><a href="tel:0753658038">{PHONE}</a> · <a href={INSTAGRAM}>Instagram</a></dd></div></dl></section>
  <section className="keywords"><details><summary>関連する検索語 / Related searches</summary><div><h3>日本語</h3><p>{jp.join("・")}</p><h3>English</h3><p>{en.join(" · ")}</p></div></details></section></main>
  <footer><div className="brand">CRAFT <span>CLUB</span></div><p>{NAME}</p><p>{ADDRESS}<br/>{PHONE}</p><p>火曜日〜土曜日 19:00〜翌2:00／日曜日・月曜日 定休</p></footer>
  </>}
